[engine]
description = "The kodanuki game engine."
path        = "engine/"
depends     = ["vulkan", "glfw"]
library     = true

[kodanuki]
description = "The upcoming kodanuki game."
path        = "source/kodanuki/"
depends     = ["kodanuki.engine", "vulkan", "glfw"]
library     = false

[unittest]
description = "Unittests for the kodanuki engine."
path        = "source/unittest/"
depends     = ["kodanuki.engine"]
library     = false

[tetris]
description = "The tetris side project."
path        = "source/tetris/"
depends     = ["kodanuki.engine", "ncurses"]
library     = false
