[engine]
description = "The kodanuki game engine."
path        = "engine/"
depends     = []
library     = true

[kodanuki]
description = "The upcoming kodanuki game."
path        = "kodanuki/"
depends     = ["kodanuki.engine", "kodanuki.opengl", "kodanuki.vulkan",
				"glfw", "GL", "GLEW"]
library     = false

[unittest]
description = "Unittests for the kodanuki engine."
path        = "unittest/"
depends     = ["kodanuki.engine"]
library     = false

# Side projects and plugins that can be used inside the game!
[tetris]
description = "The game tetris with multiple boards simultaneously."
path        = "plugin/tetris/"
depends     = ["kodanuki.engine", "ncurses"]
library     = false

[vulkan]
description = "An renderer that uses vulkan and glfw."
path		= "plugin/vulkan/"
depends		= ["kodanuki.engine", "glfw", "vulkan"]
library		= true

[opengl]
description = "An renderer that uses opengl and glfw."
path		= "plugin/opengl/"
depends		= ["kodanuki.engine", "glfw", "GL", "GLEW"]
library     = true

