[engine]
description = "The kodanuki game engine."
path        = "engine/"
depends     = ["vulkan", "sfml-window"]
library     = true

[kodanuki]
description = "The upcoming kodanuki game."
path        = "source/kodanuki/"
depends     = ["kodanuki.engine", "vulkan", "sfml-window", "sfml-system"]
library     = false

[unittest]
description = "Unittests for the kodanuki engine."
path        = "source/unittest/"
depends     = ["kodanuki.engine", "vulkan"]
library     = false

[perftest]
description = "Performance tests for the kodanuki engine."
path        = "source/perftest/"
depends     = ["kodanuki.engine", "vulkan"]
library     = false

[tetris]
description = "The tetris side project for the multiboard tetris game."
path        = "source/tetris/"
depends     = ["kodanuki.engine", "ncurses"]
library     = false

[strexpr]
description = "Some methods working on strings for university."
path        = "source/strexpr"
depends     = []
library     = false
